### ISSUE TITLE
[Bug] iPhone 7 ios 10 Crash

### ISSUE THREAD

**Issue by ThaumicMekanism** [nspire-emus/firebird#102]
I am experiencing a crash on my iPhone 7 running ios 10.2. I know the files I have work since I can run it fine on my PC and also on one of the versions of the app you had built in this thread: https://github.com/nspire-emus/firebird/issues/64
I am not jailbroken and only the link they have to an older version build in that thread which does work. Do you think it is still a JIT issue? Ill try to get the crash log but Idk how. Thanks

**Comment by adriweb** [comment]
It might be indeed.
Hopefully there will be another release soon, in which I'll provide more iOS builds (jit/nojit at least). That said, I only have a 64bit iPhone to test with (iPhone 7 with iOS 11), and Qt doesn't like 64bit much...

**Comment by adriweb** [comment]
A bit of a re-post, but we will hopefully release a new version soon, it might fix it. I'll try to upload a test release here first.

In the meantime, I shall remind that due to a bug apparently in ARM64 Qt libraries, Firebird-Emu won't work on iOS11+.

**Comment by ThaumicMekanism** [comment]
I'm on ios 10 if you want me to test it. I have an iphone 7+ on ios 10.2

**Comment by adriweb** [comment]
Here's something to try (arm64 JIT version. iOS 10 minimum): [firebird-emu-iOS_1.4-test.ipa.zip (JIT)](https://github.com/nspire-emus/firebird/files/1435158/firebird-emu-iOS_1.4-test.ipa.zip)

I'll upload the noJIT version later.

Note: on my non-jailbroken iPhone 7 running iOS 11.1, the noJIT version works (but rather slowly, as expected), but the JIT version does not (crashes during initial JIT code running).
Note 2: because Qt appears to be broken with arm64, there are some weird workarounds in place, that allow things to run, but don't be surprised about odd characters/symbols in the GUI.

**Comment by adriweb** [comment]
Okay, I was able to make some builds (and with iOS 9 compatibility in theory):

32bit JIT and noJIT: [firebird_iOS_32bit.zip](https://github.com/nspire-emus/firebird/files/1435764/firebird_iOS_32bit.zip)
64bit JIT and noJIT: [firebird_iOS_64bit.zip](https://github.com/nspire-emus/firebird/files/1435765/firebird_iOS_64bit.zip)

**Comment by ThaumicMekanism** [comment]
Ok I'll test it tonight.

**Comment by adriweb** [comment]
OK we figured more things out and were able to get the JIT running, so expect more builds "soon™"

**Comment by adriweb** [comment]
Please try the [latest release](https://github.com/nspire-emus/firebird/releases/latest) and reopen the issue if needed (generic comment, might not be 100% related)
