### ISSUE TITLE
Build failures on ppc64, i686 architectures

### ISSUE THREAD

**Issue by TC01** [nspire-emus/firebird#127]
Perhaps this is expected/known, but I just tried to build firebird-emu for Fedora (well, RPM Fusion actually) and the build failed on two architectures-- 32-bit x86 and 64-bit Big Endian PowerPC.

* [ppc64 build log](http://koji.rpmfusion.org/kojifiles/work/tasks/6628/226628/build.log)

The build fails with this error:

```
core/emu.cpp:154:10: error: #error "Not implemented"
         #error "Not implemented"
```

Which makes me think it may be expected?

* [i686 build log](http://koji.rpmfusion.org/kojifiles/work/tasks/6629/226629/build.log)

This one is stranger-- it seems the parameter AC_FLAGS does not get declared when building for 32-bit x86? The first failure is:

```
In file included from core/asmcode.h:6,
                 from core/asmcode.c:1:
core/asmcode.c: In function 'read_word':
core/asmcode.c:17:25: error: 'AC_FLAGS' undeclared (first use in this function); did you mean 'RAM_FLAGS'?
     if(unlikely(entry & AC_FLAGS))
```

For the moment, I will simply build the package with these architectures excluded, but I thought I should file a ticket.

**Comment by Vogtinator** [comment]
> Which makes me think it may be expected?

Yes, Firebird requires little endian. ppc64le should build and work fine.
It could probably be fixed, but it's not trivial (needs conversion macros all over the place) and I guess there arent (m)any users on ppc64 anyway.

> This one is stranger-- it seems the parameter AC_FLAGS does not get declared when building for 32-bit x86? The first failure is:

That is intentional: https://github.com/nspire-emus/firebird/blob/807a87b17d303628b6bab2d5311d4e6d73dc30ea/core/mmu.h#L19

asmcode.c shouldn't be built on x86 at all. I'll try to fix that.
