### ISSUE TITLE
Update binaries in release

### ISSUE THREAD

**Issue by Virility** [nspire-emus/firebird#132]
I would appreciate it if you could update the binaries on the release since there has been 88 commits since the last one in Nov 4, 2017. Thank you!

**Comment by adriweb** [comment]
A release isn’t yet ready, but you can find some “nightly” windows builds here by @jacobly0 : http://jacobly.com/firebird/master/latest/ (you can trim the .gz suffix off the links, your browser will understand).
For other platforms, well I guess you’ll have to build it yourself in the meantime!

**Comment by Vogtinator** [comment]
There are unstable builds for linux distros on

https://software.opensuse.org//download.html?project=home%3AVogtinator%3Afirebird-emu%3Aunstable&package=firebird-emu

**Comment by Jo900** [comment]
Any news about upcoming versions ? time ago i asked for two useful features:

- sounds on pressing keys
- qwerty layout for keyboard

this project seems kinda abandoned... you guys should officialy work for texas and make an official emulator on the store at payment as work for hp prime.

**Comment by adriweb** [comment]
It's definitely not abandoned as you can see in the commits history: https://github.com/nspire-emus/firebird/commits/master
But yeah, for mobile at leasts, building it yourself from source is the best way to get the latest stuff. Otherwise, look at the link on jacobly's site I linked above, for Windows.

For key pressing sound, yeah we started looking into it but never finished - PRs are welcome :)

**Comment by Vogtinator** [comment]
1.5 is out.
