### ISSUE TITLE
Cannot install on iphone6s

### ISSUE THREAD

**Issue by KondeU** [nspire-emus/firebird#145]
After I dragged to itunes and then installed it to my iphone6s, the icon is gray and I can't run it. I tried to reinstall multiple times and reboot my phone, but no effect. Could you give me a help? Thanks a lot.

**Comment by adriweb** [comment]
Not sure what to do there... If you have Xcode, can you dragndrop the ipa in the apps list of the Devices window?

**Comment by KondeU** [comment]
Thanks for your answer. I don't have Xcode on my computer, but I tried to install it as a developer with Cydia Impactor today, but it still failed and I gave up... Maybe I can try to download Xcode and try to install again this weekend...

**Comment by adriweb** [comment]
It's possibly because of stricter apple policies over time (I mean, frankly, unless the phone is jail broken I don't even know how installing the ipa managed to work all these years... in theory it's not code signed for external sharing - can't do that for unlimited/any devices, only specific ones :p) 
That said if you're going to install Xcode and it still doesn't work, you can try building it. You'll also need to install the Qt sdk too, but anyway I can give you the few steps.

**Comment by adriweb** [comment]
Closing as I can't really do anything about it myself except putting it on the App Store, but Apple (and probably TI) wouldn't like that :)
Potential workaround for jailbroken devices would be to work on that: https://github.com/nspire-emus/firebird/issues/74

Maybe try with cydia impactor or any other method that may work with local IPAs now... with the latest release ?
