### ISSUE TITLE
Issue dereferencing 64 bit pointers

### ISSUE THREAD

**Issue by rayzerbrain** [nspire-emus/firebird#306]
Hello,

This code segment below is outputting a seemingly garbage value (290982432, consistently), when it should be giving 4. I tested this with a freshly generated project, on an emulated cx cas os version 4.5.4. I'm fairly new to c programming, so apologies if this a problem on my end.

```c
int main() {
    uint64_t num = 4;
    uint64_t* ptr = &num;
    printf("%llu\n", *ptr);
    return 0;
}
```

**Comment by Vogtinator** [comment]
Confirmed. This is not a bug in firebird though but in the Ndless SDK, most likely in newlib. It appears like `%llu` is treated like `%lu` and it expects an `uint32_t` in `r1` instead of a `uint64_t` split across `r2` and `r3`. The compiled code does not set `r1` explicitly, so it contains the location of `argv` when `printf` is called.

**Comment by Vogtinator** [comment]
That's simply because `--enable-newlib-io-long-long` is not enabled by default. I'll check how much bigger libc will with that.

**Comment by Vogtinator** [comment]
Fixed: https://github.com/ndless-nspire/Ndless/commit/7cf42395b1137ef303c2164c210afc6cd145d4e2
