### ISSUE TITLE
Provide a way to share snapshots

### ISSUE THREAD

**Issue by UnknwnDev** [nspire-emus/firebird#309]
Is there a way I could sent snapshoots to others without it loading with my file system in mind?

**Comment by Vogtinator** [comment]
Unfortunately not, the snapshots themselves contain paths to the used boot1 and flash files. This is so that you don't have to select those manually when loading a snapshot and to make it possible to use a snapshot location for multiple kits, without risking that loading a snapshot with the wrong kit corrupts data. As a workaround, you can decompress the snapshot (gzip) and edit the paths by hand.

One option would be to put relative paths into the snapshot, so if they are stored together they can be moved elsewhere and still work.

Another option would be to allow loading a snapshot from a kit with an option to override the paths set in the snapshot.

**Comment by UnknwnDev** [comment]
How would I go about decompressing the gzip on windows?

**Comment by UnknwnDev** [comment]
I mannged to find a solution by placing the fire bird folder in C: and having the boot and flash in it.
