### ISSUE TITLE
iOS recompile and deploy

### ISSUE THREAD

**Issue by claywd1210** [nspire-emus/firebird#38]
I'm a little lost on what code to crab and throw in Xcode. Do you already have an Xcode project somewhere on here or do I need to create my own. If so, then do I just use the master source code for the iOS app?

**Comment by adriweb** [comment]
There's no `.xcodeproj` file since it's created by Qt [Creator] at build.
For a JIT build, you can try to follow the instructions at https://github.com/nspire-emus/firebird#a-special-case-ios-with-translation-jit-enabled .
If that doesn't work (I probably need to update it to the latest things...), open the `.xcodeproj` file from the build folder, add the asmcode_arm.S file to the target, and build (&run/deploy).
(It was talked about in more details on issue #37 as well)

**Comment by bob8490** [comment]
Clay - did you ever get this going?

**Comment by adriweb** [comment]
Well, did you follow the instructions?
IIRC, getting an .xcodeproj is just a matter of opening the .pro with Qt Creator, choosing the iOS toolchain/kit, and building.

**Comment by bob8490** [comment]
I did - I spent a few days trying to make it work.  It was a while ago, so perhaps I'd have more luck now, but I was trying to get it to work on iPhone 6, which is 64 bit, and it was just not going well.
It worked fine on my iPad.

**Comment by adriweb** [comment]
Oh yeah, you're the guy from issue #37 - I'll reply there.

**Comment by bob8490** [comment]
I am, haha.
Thanks.
