### ISSUE TITLE
Precompiled binary for the iPhone/iPad version.

### ISSUE THREAD

**Issue by p0wer0n** [nspire-emus/firebird#6]
I cannot compile the iOS version using QT or Terminal on Yosemite. Can you please provide a precompiled iOS binary (I can sign it) in the releases, or here? Thanks!

**Comment by adriweb** [comment]
There is a known issue with the build process of a JIT-enabled binary, which I suppose is what you may have encountered.
I have added specific instructions for this in the readme: https://github.com/nspire-emus/firebird/blob/master/README.md#a-special-case-ios-with-translation-jit-enabled

If this still doesn't work for you somehow, I guess I can indeed try to provide a binary directly (though I'll have to see how to generate an unsigned one so that you can sign it yourself afterwards)

**Comment by p0wer0n** [comment]
I got the binary to compile by changing "TRANSLATION_ENABLED" from "true" to "false." Thanks for the help

**Comment by adriweb** [comment]
I've uploaded a non-codesigned build on the release page: https://github.com/nspire-emus/firebird/releases/tag/v0.20
It has JIT enabled, so jailbreak required (and, well, it was already since the .ipa would need AppSync...)
Let me know if that works for you, I can't really test it.
