### ISSUE TITLE
Issues with new Mobile UI

### ISSUE THREAD

**Issue by gchiozzi** [nspire-emus/firebird#85]
Hi Fabian,
I have just installed the redesigned Mobile UI 1.3.
Great job.
I have noticed a couple of issues (some possibly there since the previous versions):
Notice that I am trying out the Mobile UI on Windows for the 1st time, before I have always been using the normal UI.
- On my Samsung Notes 10.1 tablet, in landscape mode it does not scale well any more and the last row of numeric keypad row (the one with the buttons:  0 . (-) ) is cut out and I always have to scroll.
Considering that the buttons are huge on 10inch tablet, this is really a pity.
The UI would actually look pretty usable even showing the complete keyboard
On my Samsung S4 Mini I see the complete numeric pad.
It is probably due to the different aspect ratio of the displays, but there is nothing bad in having black bars on the side of the keypad to see more on tablet displays, preserving the original aspect ration
- On Android, if 
   -the LCD of the TI is turned off,
   - I go from portrait to landscape 
   - then back again to portrait, 
   the keyboard disappears.
- The Mobile UI Configuration does not have the Emulation->"Save snapshot on shutdown" option, that is very convenient. In Windows with the standard UI this option works very well. Is there any special reason why this option is not available in the Mobile UI?

**Comment by Vogtinator** [comment]
> I have just installed the redesigned Mobile UI 1.3.
Great job.

Thanks!

> Notice that I am trying out the Mobile UI on Windows for the 1st time, before I have always been using the normal UI.

Out of curiosity, why?

> On Android, if the LCD of the TI is turned off, I go from portrait to landscape then back again to portrait, the keyboard disappears.

Hm, I thought I fixed that. Can you upload the adb log somewhere?

> On my Samsung Notes 10.1 tablet, in landscape mode it does not scale well any more and the last row of numeric keypad row (the one with the buttons: 0 . (-) ) is cut out and I always have to scroll.
Considering that the buttons are huge on 10inch tablet, this is really a pity.
The UI would actually look pretty usable even showing the complete keyboard
On my Samsung S4 Mini I see the complete numeric pad.
It is probably due to the different aspect ratio of the displays, but there is nothing bad in having black bars on the side of the keypad to see more on tablet displays, preserving the original aspect ration

I see, doesn't the landscape mode work well enough?

> The Mobile UI Configuration does not have the Emulation->"Save snapshot on shutdown" option, that is very convenient. In Windows with the standard UI this option works very well. Is there any special reason why this option is not available in the Mobile UI?

Yes, it's not possible to implement this properly on Android and iOS, so I never added support for it in the mobile UI. On Android and iOS, the application can get suspended in the background and killed at any time, with just a few milliseconds of time for saving stuff. That is not enough to generate a snapshot file.

**Comment by gchiozzi** [comment]
Hi Fabian,

My replies inline below,

     Thanks!

                 Gianluca

**Comment by Vogtinator** [comment]
Your response lacks formatting and all of the links are broken...

> Being just one window looks more compact/nicer and scales better that the standard one, with the dockable windows. I have a vague remembrance of an option in one of the first versions of an option for a different layout, without the dockable windows, but I do not find it any more.

You can just drag all dock windows on top of each other to get the old tab UI back.

The mobile UI isn't really meant to be used on desktops (although it definitely works as that's how I develop it) for multiple reasons:
- No proper keyboard support (navigation, buttons)
- Not really customizable layout
- Needs a touch screen to be usable

> Most of the times I just do trivial calculations and therefore it would be sufficient to see ad least the whole numeric pad (like on the phone). Without that, it is really annoying.

Hm, maybe I can add an option to fix the keypad to the available height instead of the available width.

**Comment by gchiozzi** [comment]
Sorry, I replied directly from Outlook and probably the formatting got lost with the ingestion in the discussion repository.

Having an option to fix the keypad to the height if probably going to work very well. It looks to me an excellent idea. 

I attach here the two snapshots of the UI that got lost in my previous post, the mobile and the normal one.
What I was trying to say about the docking in the normal UI is that it always looks like two windows, just inside a bigger window. And, no matter how I try to resize, there is always a huge border around.

![normal](https://cloud.githubusercontent.com/assets/10168547/26114156/d699a6b4-3a5c-11e7-8dd1-f927cedc57c9.png)

The Mobile UI looks much nicer in my machine.

![mobile](https://cloud.githubusercontent.com/assets/10168547/26114151/d1693df8-3a5c-11e7-9cee-1b171d5b2c85.png)

Am I doing something wrong?

Really thanks, you are really very quick in responding!

     Gianluca

**Comment by Vogtinator** [comment]
> Am I doing something wrong?

Not sure, does the keypad or the LCD restrict the minimal width?

**Comment by gchiozzi** [comment]
It is the LCD, but also around that the borders are very big.
Then there dragbar of the Keypad window.

Attached is the best I can get.

![image](https://cloud.githubusercontent.com/assets/10168547/26141756/bca6f4b0-3add-11e7-8af5-3ccb90cbc739.png)

It is still very usable, but the Mobile one looks much nicer.

      Gianluca

**Comment by Vogtinator** [comment]
I pushed two commits that should make the appearance a bit nicer by getting rid of borders around the LCD altogether. Can you test those? If you need a windows build you can ask @adriweb

**Comment by gchiozzi** [comment]
Yes, I would need a windows build, since I do not have the build chain installed/configured on any machine.
If @adriweb  can point me to a place where I can download it from, it would be good.

**Comment by adriweb** [comment]
Yeah I'll rebuild the mac/ios/windows versions sometime soon

**Comment by mshroye1** [comment]
I'm having an issue with this program on my kindle fire (yes technicality its not meant for kindle but my fire allows me to install android apps) every time I put the boot and flash files in the emulator the thing will go through the installation stuff but then the LCD shuts off and I can't get it to come in to finish the installation so I can use it 

Can you help me

**Comment by Vogtinator** [comment]
@mshroye1 Please open a separate issue for that and provide some more information.

**Comment by adriweb** [comment]
Looks fixed - to re-open if needed.
